#FROM frolvlad/alpine-python3
FROM http:v4
COPY . /src
#COPY geckodriver /usr/local/bin

#RUN apk --update add openssl ca-certificates py-openssl wget
#RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python3-dev build-base \
#  && pip3 install --upgrade pip \
#  && pip3 install numpy \
#  && pip3 install selenium \
#  && pip3 install pyvirtualdisplay \
#  && apk del build-dependencies
#RUN chmod +x /src/geckodriver
#CMD ["python", "/src/int/main.py"]

